In [1]:
import numpy as np

## Numpy kütüphanesinde 10 adet seçtikleri fonksiyonu açıklayarak kullanım örneği olan jupyter notebook ile paylaşılacak.

#### 1-Dizi oluşturmak için np.array() fonksiyonu kullanılır.

In [2]:
n1 = np.array([1, 2, 3, 4, 5])
print(n1)

[1 2 3 4 5]


#### 2-Dizideki tüm elemanların toplamını döndürmek için np.sum() fonksiyonu kullanılır.

In [6]:
n2 =np.array([[1,2,3],[4,5,6]])
toplam=np.sum(n2)
print(toplam)

21


#### 3-Dizideki elemanların ortalamasını almak için np.mean() fonksiyonu kullanılır.

In [8]:
n3=np.array([5,10,15,20,25])
ortalama=np.mean(n3)
print(ortalama)

15.0


#### 4-Dizideki en büyük elemanı bulmak için np.max() kullanılır.

In [9]:
en_büyük_sayı=np.max(n3)
print(en_büyük_sayı)

25


#### 5-Dizideki en küçük sayıyı bulmak için kullanılan fonksiyon ise np.min()'dir.

In [10]:
en_küçük_sayı=np.min(n3)
print(en_küçük_sayı)

5


#### 6-Eğer diziyi yeniden şekillendiremek istersek yani boyutunu şekillendirmek istersek np.reshape() fonksiyonunu kullanırız.
##### bu fonksiyon sadece boyutu istenilen yeni boyuta göre değiştirir eleman sayısı değişmez!

In [18]:
n4=np.array([10,20,30,40,50,60,70,80])
reshape=n4.reshape(2,4)
print(reshape)

[[10 20 30 40]
 [50 60 70 80]]


#### 7-Verilen 2 sayının arasındaki sayıları arraye çeviren ve yazan  np.arange() fonksiyonudur.

In [23]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
#istersem atalatarakte ilerletebilirim.

In [26]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

#### 8-np.zeros() fonksiyonu belirttiğiniz miktar kadar 0'lardan oluşan bir Array yaratacaktır.

In [27]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### 9-np.random.randint() --> Bu fonksiyon ile belirlediğimiz sayılar arasında belirlediğimiz kadar rasgele sayı çıktısı vermeyi sağlıyor.

In [31]:
np.random.randint(10,300,6) #10 ile 300 arasında rasgele 5 tane sayıyı ver demek istedik.o kısma bir şey yazmazsak 1 tane rasgele sayı verirdi.

array([ 50, 289, 172,  48, 185, 109], dtype=int32)

#### 9.1-np.random.rand() --> bu ise 0 ile 1 arasondaki sayıları rasgele vericektir.

In [30]:
np.random.rand(3)

array([0.21032952, 0.42612554, 0.5352973 ])

#### 10-Determinant alabilmek için np.linalg.det() fonksiyonunu kullanıyoruz.

In [37]:
np5=np.array([[1,2],[3,4]])
np.linalg.det(np5)

np.float64(-2.0000000000000004)